name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: manishkatyan/strapi:cypress-base

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: bash copy.sh
