name: Node.js CI

on:
  push:
    branches: [packet-update]
  pull_request:
    branches: [main]

jobs:
  build:
    container:
      runs-on: ubuntu-latest
      image: nishekh/bbbstrapi

    steps:
      - run: bash copy.sh
