name: Node.js CI

on:
  push:
    branches: [packet-update]
  pull_request:
    branches: [main]
env:
  COMMIT_ID: ${{ github.sha }}

jobs:
  dockerbuildandpush:
    runs-on: ubuntu-latest

    steps:
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: nishekh/bbbstrapi:${{ env.COMMIT_ID }}
  runtest:
    runs-on: ubuntu-latest
    container:
      image: nishekh/bbbstrapi:${{ env.COMMIT_ID }}

    steps:
      - run: npm run develop &
      - run: sleep 50
      - run: cd /usr/src/app/src/plugins/bigbluebutton/;npx cypress run --browser firefox
